services:
  frontend:
    container_name: frontend
    image: abhishekchauhandev/devboard-frontend:v1.1
    ports:
      - "8080:4173"
    networks:
      - devboard-net
    depends_on:
      - backend

  backend:
    container_name: backend
    image: abhishekchauhandev/devboard-backend:v1.1
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://devboard:devboard@postgres:5432/devboard?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devboard-net

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=devboard
      - POSTGRES_PASSWORD=devboard
      - POSTGRES_DB=devboard
    ports:
      - "5432:5432"
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devboard", "-d", "devboard"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - devboard-net

volumes:
  postgres-data:

networks:
  devboard-net:
