apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devboard
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # Uncomment the nodeSelector if you want to deploy the backend on a specific node with ssd disk. The affinity section is currently set to require scheduling on a node with hostname "desktop-worker2".
      # nodeSelector:
      #   disk: ssd
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - desktop-worker2
      containers:
      - name: backend
        image: abhishekchauhandev/devboard-backend:v1.4
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"   
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_USER
        - name: POSTGRES_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable"
        ports:
        - containerPort: 8080