apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devboard
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Uncomment the nodeSelector if you want to deploy the frontend on a specific node with hdd disk. The affinity section is currently set to prefer scheduling on a node with hostname "desktop-worker".
      # nodeSelector:
      #   disk: hdd
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - desktop-worker
      containers:
      - name: frontend
        image: abhishekchauhandev/devboard-frontend:v1.4
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        ports:
        - containerPort: 4173