apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devboard
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Uncomment the nodeSelector if you want to deploy the frontend on a specific node with hdd disk.

      # nodeSelector:
      #   disk: hdd

      # Uncomment the affinity section if you want to deploy the frontend on a specific node with hostname "desktop-worker".

      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - desktop-worker

      # Implemented pod anti-affinity to ensure that the frontend and backend pods are not scheduled on the same node, while also implementing pod affinity to ensure that the frontend pod is scheduled on the same node as the postgres pod.

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"

        podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - postgres
              topologyKey: "kubernetes.io/hostname"      

      containers:
      - name: frontend
        image: abhishekchauhandev/devboard-frontend:v1.4
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        ports:
        - containerPort: 4173