apiVersion: v1
kind: LimitRange
metadata:
  name: devboard
  namespace: devboard
spec:
  limits:
  - max: # Max cpu limit for a container
      cpu: "800m"
    min: # Min cpu limit for a container
      cpu: "200m"
    type: Container
