apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.backend.name }}
  ports:
    - protocol: {{ .Values.service.backend.protocol }}
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}