apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.deployment.backend.name }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.PodDisruptionBudget.backend.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.backend.name }}