apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.deployment.postgres.environment.POSTGRES_DB | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.deployment.postgres.environment.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_USER: {{ .Values.deployment.postgres.environment.POSTGRES_USER | b64enc }}
kind: Secret
metadata:
  name: db-creds
  namespace: {{ .Values.namespace }}
