apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.frontend.name }}
  ports:
    - protocol: {{ .Values.service.frontend.protocol }}
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}