apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.frontend.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.frontend.name }}
        image: {{ .Values.deployment.frontend.image }}
        resources:
          requests:
            memory: {{ .Values.deployment.frontend.resources.requests.memory }}
            cpu: {{ .Values.deployment.frontend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.frontend.resources.limits.memory }}
            cpu: {{ .Values.deployment.frontend.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.deployment.frontend.port }}