apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.deployment.frontend.name }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.frontend.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.frontend.name }}