apiVersion: v1
data:
  nginx.conf: "# Default server configuration\n\nserver {\n\tlisten 80 default_server;\n\tlisten
    [::]:80 default_server;\n\n\t# Add index.php to the list if you are using PHP\n\tindex
    index.html index.htm index.nginx-debian.html;\n\n\tserver_name _;\n\n\tlocation
    / {\n\t\tproxy_pass http://frontend:8080;\n\t\tproxy_set_header Host $host$is_request_port$request_port;\n\t\tproxy_set_header
    X-Real-IP $remote_addr;\n\t\tproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n\t\tproxy_set_header
    X-Forwarded-Proto $scheme;\n\t}\n\n\tlocation /api/ {\n\t\tproxy_pass http://backend:8081/;\n\t\tproxy_set_header
    Host $host$is_request_port$request_port;\n\t\tproxy_set_header X-Real-IP $remote_addr;\n\t\tproxy_set_header
    X-Forwarded-For $proxy_add_x_forwarded_for;\n\t\tproxy_set_header X-Forwarded-Proto
    $scheme;\n\t}\n\n}\n"
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devboard