apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.nginx.name }}
  ports:
    - protocol: {{ .Values.service.nginx.protocol }}
      port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.targetPort }}