apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.nginx.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.nginx.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.nginx.name }}
        image: {{ .Values.deployment.nginx.image }}
        resources:
          requests:
            memory: {{ .Values.deployment.nginx.resources.requests.memory }}
            cpu: {{ .Values.deployment.nginx.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.nginx.resources.limits.memory }}
            cpu: {{ .Values.deployment.nginx.resources.limits.cpu }}
        command: ["/docker-entrypoint.sh"]    
        args:
        - nginx
        - -g
        - "daemon off;"
        ports:
        - containerPort: {{ .Values.deployment.nginx.port }}
        volumeMounts:
        - name: {{ .Values.deployment.nginx.name }}-config
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: nginx.conf
          readOnly: true 
      volumes:
      - name: {{ .Values.deployment.nginx.name }}-config
        configMap:
          name: {{ .Values.deployment.nginx.name }}-config