apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.postgres.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.postgres.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.postgres.name }}
        image: {{ .Values.deployment.postgres.image }}
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          failureThreshold: {{ .Values.deployment.postgres.failureThreshold }}
          periodSeconds: {{ .Values.deployment.postgres.periodSeconds }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          initialDelaySeconds: {{ .Values.deployment.postgres.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.postgres.periodSeconds }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          periodSeconds: {{ .Values.deployment.postgres.periodSeconds }}     
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: POSTGRES_USER
        resources:
          requests:
            memory: {{ .Values.deployment.postgres.resources.requests.memory }}
            cpu: {{ .Values.deployment.postgres.resources.requests.cpu }}  
          limits:
            memory: {{ .Values.deployment.postgres.resources.limits.memory }}
            cpu: {{ .Values.deployment.postgres.resources.limits.cpu }}      
        ports:
        - containerPort: {{ .Values.deployment.postgres.port }}
        volumeMounts:
        - name: db-scripts
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
        - mountPath: "/var/lib/postgresql/data"
          name: data  
      volumes:
      - name: db-scripts
        configMap:
          name: db-scripts
      - name: data
        persistentVolumeClaim:
          claimName: devboard-pvc