apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.postgres.name }}
  ports:
    - protocol: {{ .Values.service.postgres.protocol }}
      port: {{ .Values.service.postgres.port}}
      targetPort: {{ .Values.service.postgres.targetPort}}