apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: devboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: devboard-pvc
        - name: db-scripts
          configMap:
            name: db-scripts
      containers:
      - image: postgres:16-alpine
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
          subPath: postgres-data
        - mountPath: "/docker-entrypoint-initdb.d"
          name: db-scripts
        name: postgres
        ports:
        - containerPort: 5432
        resources: 
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
