apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devboard-pvc
  namespace: devboard
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi