apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-08-01T09:43:48Z"
  name: devboard
  namespace: devboard
  resourceVersion: "13935"
  uid: 4a0ffb4b-60dc-48f1-bdf0-03b1178e8755
imagePullSecrets:
  - name: imagepullsecret