# Goal - In this workflow, we will implement Continuous Integration (CI) of frontend.
# Steps:
# 1. Checkout the code from the repository.
# 2. Setup Node.js environment.
# 3. Install dependencies.
# 4. Lint the code.
# 5. Run tests.
# 6. Build the code.

name: Continuous Integration

on:
  push:
    branches:
      - day1

jobs:

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          package-manager-cache: true
          cache-dependency-path: './frontend'

      - name: Install dependencies
        run: |
          cd frontend
          npm install      