# Goal - In this workflow, we will implement Continuous Integration (CI) of frontend.
# Steps:
# 1. Checkout the code from the repository.
# 2. Install dependencies.
# 3. Lint the code.
# 4. Run tests.
# 5. Build the code.

name: Continuous Integration

on:
  push:
    branches:
      - day1

jobs:

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

