name: CI

on:
  push:
    branches:
      - install_packages

jobs:
  frontend:
    uses: ./.github/workflows/Build-and-Test-Frontend.yml
    secrets: inherit
  backend:
    uses: ./.github/workflows/Build-and-Test-Backend.yml
    secrets: inherit